export const GET_CATEGORIES_REQUESTING = 'GET_CATEGORIES_REQUESTING';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_ERROR = 'GET_CATEGORIES_ERROR';

export const GET_POPULAR_ACTIVITIES_REQUESTING = "GET_POPULAR_ACTIVITIES_REQUESTING";
export const GET_POPULAR_ACTIVITIES_SUCCESS = "GET_POPULAR_ACTIVITIES_SUCCESS";
export const GET_POPULAR_ACTIVITIES_ERROR = "GET_POPULAR_ACTIVITIES_ERROR";

export const GET_POPULAR_LODGING_REQUESTING = "GET_POPULAR_LODGING_REQUESTING";
export const GET_POPULAR_LODGING_SUCCESS = "GET_POPULAR_LODGING_SUCCESS";
export const GET_POPULAR_LODGING_ERROR = "GET_POPULAR_LODGING_ERROR";

export const GET_POPULAR_CENTERS_REQUESTING = "GET_POPULAR_CENTERS_REQUESTING";
export const GET_POPULAR_CENTERS_SUCCESS = "GET_POPULAR_CENTERS_SUCCESS";
export const GET_POPULAR_CENTERS_ERROR = "GET_POPULAR_CENTERS_ERROR";

export const HOME_PAGE_RESET_STATE = "HOME_PAGE_RESET_STATE";






