export const USER_GET_REQUESTING = 'USER_GET_REQUESTING';
export const USER_GET_SUCCESS = 'USER_GET_SUCCESS';
export const USER_GET_ERROR = 'USER_GET_ERROR';

export const USER_UPDATE_REQUESTING = 'USER_UPDATE_REQUESTING';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_ERROR = 'USER_UPDATE_ERROR';

export const USER_CHANGE_FORM = 'USER_CHANGE_FORM';

export const USER_MODAL_PHOTOS_TOGGLE = 'USER_MODAL_PHOTOS_TOGGLE';

export const USER_RESET_STATES = 'USER_RESET_STATES';
export const USER_RESET_STATES_LOGOUT = 'USER_RESET_STATES_LOGOUT';


