export const TOGGLE_ROOMS_MODAL = "TOGGLE_ROOMS_MODAL";
export const GET_LODGING_REQUESTING = "GET_LODGING_REQUESTING";
export const GET_LODGING_SUCCESS = "GET_LODGING_SUCCESS";
export const GET_LODGING_ERROR = "GET_LODGING_ERROR";

export const GET_POPULAR_ACTIVITIES_REQUESTING = "GET_POPULAR_ACTIVITIES_REQUESTING";
export const GET_POPULAR_ACTIVITIES_SUCCESS = "GET_POPULAR_ACTIVITIES_SUCCESS";
export const GET_POPULAR_ACTIVITIES_ERROR = "GET_POPULAR_ACTIVITIES_ERROR";

export const LODGING_PAGE_RESET_STATE = "LODGING_PAGE_RESET_STATE";
