export const GET_RESERVATIONS_REQUESTING = "GET_RESERVATIONS_REQUESTING";
export const GET_RESERVATIONS_SUCCESS = "GET_RESERVATIONS_SUCCESS";
export const GET_RESERVATIONS_ERROR = "GET_RESERVATIONS_ERROR";

export const RESERVATIONS_PAGE_RESET_STATE = "RESERVATIONS_PAGE_RESET_STATE";
