export const REGISTER_REQUESTING = 'REGISTER_REQUESTING';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';

export const REGISTER_CHANGE_FORM = 'REGISTER_CHANGE_FORM';
export const REGISTER_CLEAN_FORM = 'REGISTER_CLEAN_FORM';

export const REGISTER_RESET_STATE = 'REGISTER_RESET_STATE';
