export const GET_SERVICE_REQUESTING = "GET_SERVICE_REQUESTING";
export const GET_SERVICE_SUCCESS = "GET_SERVICE_SUCCESS";
export const GET_SERVICE_ERROR = "GET_SERVICE_ERROR";

export const SERVICE_PAGE_GET_POPULAR_ACTIVITIES_REQUESTING = "SERVICE_PAGE_GET_POPULAR_ACTIVITIES_REQUESTING";
export const SERVICE_PAGE_GET_POPULAR_ACTIVITIES_SUCCESS = "SERVICE_PAGE_GET_POPULAR_ACTIVITIES_SUCCESS";
export const SERVICE_PAGE_GET_POPULAR_ACTIVITIES_ERROR = "SERVICE_PAGE_GET_POPULAR_ACTIVITIES_ERROR";

export const SERVICE_PAGE_GET_POPULAR_LODGING_REQUESTING = "SERVICE_PAGE_GET_POPULAR_LODGING_REQUESTING";
export const SERVICE_PAGE_GET_POPULAR_LODGING_SUCCESS = "SERVICE_PAGE_GET_POPULAR_LODGING_SUCCESS";
export const SERVICE_PAGE_GET_POPULAR_LODGING_ERROR = "SERVICE_PAGE_GET_POPULAR_LODGING_ERROR";

export const SERVICE_PAGE_GET_QUESTIONS_REQUESTING = "SERVICE_PAGE_GET_QUESTIONS_REQUESTING";
export const SERVICE_PAGE_GET_QUESTIONS_SUCCESS = "SERVICE_PAGE_GET_QUESTIONS_SUCCESS";
export const SERVICE_PAGE_GET_QUESTIONS_ERROR = "SERVICE_PAGE_GET_QUESTIONS_ERROR";

export const SERVICE_PAGE_CHANGE_POST_QUESTION = "SERVICE_PAGE_CHANGE_POST_QUESTION";

export const SERVICE_PAGE_POST_QUESTION_REQUESTING = "SERVICE_PAGE_POST_QUESTION_REQUESTING";
export const SERVICE_PAGE_POST_QUESTION_SUCCESS = "SERVICE_PAGE_POST_QUESTION_SUCCESS";
export const SERVICE_PAGE_POST_QUESTION_ERROR = "SERVICE_PAGE_POST_QUESTION_ERROR";

export const SERVICE_PAGE_RESET_STATE = "SERVICE_PAGE_RESET_STATE";
