export const TOGGLE_WHAT_WOULD_YOU_LIKE_TO_DO_MODAL = 'TOGGLE_WHAT_WOULD_YOU_LIKE_TO_DO_MODAL';

export const SEARCH_REQUESTING = "SEARCH_REQUESTING";
export const SEARCH_SUCCESS = "SEARCH_SUCCESS";
export const SEARCH_ERROR = "SEARCH_ERROR";

export const SEARCH_CHANGE_VALUES = "SEARCH_CHANGE_VALUES";

export const GET_FILTER_OPTIONS_REQUESTING = "GET_FILTER_OPTIONS_REQUESTING";
export const GET_FILTER_OPTIONS_SUCCESS = "GET_FILTER_OPTIONS_SUCCESS";
export const GET_FILTER_OPTIONS_ERROR = "GET_FILTER_OPTIONS_ERROR";

export const FILTER_ADD_ZONE = "FILTER_ADD_ZONE";
export const FILTER_DELETE_ZONE = "FILTER_DELETE_ZONE";

export const FILTER_ADD_SERVICE = "FILTER_ADD_SERVICE";
export const FILTER_DELETE_SERVICE = "FILTER_DELETE_SERVICE";

export const FILTER_ADD_LANGUAGE = "FILTER_ADD_LANGUAGE";
export const FILTER_DELETE_LANGUAGE = "FILTER_DELETE_LANGUAGE";
export const FILTER_CLEAR = "FILTER_CLEAR";

export const SEARCH_RESET_ZONES_SERVICE_LANGUAGE = "SEARCH_RESET_ZONES_SERVICE_LANGUAGE";

export const SEARCH_ADD_DIVER = "SEARCH_ADD_DIVER";
export const SEARCH_DELETE_DIVER = "SEARCH_DELETE_DIVER";

export const SEARCH_CHANGE_PAX_VALUES = "SEARCH_CHANGE_PAX_VALUES";

export const SEARCH_RESET_STATE = "SEARCH_RESET_STATE";