export const LOGIN_REQUESTING = 'LOGIN_REQUESTING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const LOGIN_CHANGE_FORM = 'LOGIN_CHANGE_FORM';
export const LOGIN_RESET_STATES = 'LOGIN_RESET_STATES';