export const GET_CENTER_REQUESTING = "GET_CENTER_REQUESTING";
export const GET_CENTER_SUCCESS = "GET_CENTER_SUCCESS";
export const GET_CENTER_ERROR = "GET_CENTER_ERROR";

export const CENTER_PAGE_RESET_STATE = "CENTER_PAGE_RESET_STATE";
