export const TOGGLE_FILTER_MODAL = 'TOGGLE_FILTER_MODAL';

export const GET_SUBCATEGORIES_REQUESTING = "GET_SUBCATEGORIES_REQUESTING";
export const GET_SUBCATEGORIES_SUCCESS = "GET_SUBCATEGORIES_SUCCESS";
export const GET_SUBCATEGORIES_ERROR = "GET_SUBCATEGORIES_ERROR";

export const SET_DATA_RESULT = "SET_DATA_RESULT";

export const GET_SEARCH_PAGE_POPULAR_ACTIVITIES_REQUESTING = "GET_SEARCH_PAGE_POPULAR_ACTIVITIES_REQUESTING";
export const GET_SEARCH_PAGE_POPULAR_ACTIVITIES_SUCCESS = "GET_SEARCH_PAGE_POPULAR_ACTIVITIES_SUCCESS";
export const GET_SEARCH_PAGE_POPULAR_ACTIVITIES_ERROR = "GET_SEARCH_PAGE_POPULAR_ACTIVITIES_ERROR,";

export const RESULT_RESET_STATE = "RESULT_RESET_STATE";