export const GET_ZONE_REQUESTING = "GET_ZONE_REQUESTING";
export const GET_ZONE_SUCCESS = "GET_ZONE_SUCCESS";
export const GET_ZONE_ERROR = "GET_ZONE_ERROR";

export const GET_POPULAR_ACTIVITIES_REQUESTING = "GET_POPULAR_ACTIVITIES_REQUESTING";
export const GET_POPULAR_ACTIVITIES_SUCCESS = "GET_POPULAR_ACTIVITIES_SUCCESS";
export const GET_POPULAR_ACTIVITIES_ERROR = "GET_POPULAR_ACTIVITIES_ERROR";

export const ZONE_PAGE_RESET_STATE = "ZONE_PAGE_RESET_STATE";
